services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/bin/database -port 50051 -data-limit 1000000
    networks:
      - iiot-network
    ports:
      - "50051:50051"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50051"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/bin/server -host 0.0.0.0 -port 8080 -db-addr database:50051
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - iiot-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  #our MQTT Broker (Mosquitto)
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"  #MQTT port
      - "9001:9001"  #WebSocket port
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - iiot-network
    restart: unless-stopped

  #gateway now subscribes to MQTT instead of generating data
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/bin/gateway -server-host server -server-port 8080 -mqtt-host mqtt-broker -mqtt-port 1883
    depends_on:
      - server
      - mqtt-broker
    networks:
      - iiot-network
    restart: unless-stopped

  sensors:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/bin/sensor -mqtt-host mqtt-broker -mqtt-port 1883 -instances 3 -duration 300
    depends_on:
      - mqtt-broker
    networks:
      - iiot-network
    deploy:
      replicas: 2
    restart: unless-stopped

networks:
  iiot-network:
    driver: bridge