version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/bin/server -host 0.0.0.0 -port 8080
    ports:
      - "8080:8080"
    networks:
      - iiot-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/bin/gateway -server-host server -server-port 8080 -instances 3
    depends_on:
      server:
        condition: service_healthy
    networks:
      - iiot-network
    deploy:
      replicas: 2

networks:
  iiot-network:
    driver: bridge